sudo: required

language: go

env:
  global:
    - DOCKER_TAG: ${TRAVIS_TAG}

services:
  - docker

jobs:
  include:
    - stage: tests
      script:
        - make test
    - stage: push image
      script:
        - make push GOOS=linux DOCKER_NAMESPACE=${DOCKER_NAMESPACE} DOCKER_TAG=${DOCKER_TAG} DOCKER_USER=${DOCKER_USER} DOCKER_PASSWORD=${DOCKER_PASSWORD}
      if: tag IS present
