kind: ConfigMap
apiVersion: v1
metadata:
  name: "{{ include "slack-duty-bot.fullname" . }}"
data:
  config.yaml: |-
    slack:
      keyword:
      {{- range $keyword := .Values.configuration.keywords }}
        - {{ $keyword | quote}}
      {{- end }}
    duties:
      - [ {{- join "," .Values.dutyUsers.sunday -}} ]
      - [ {{- join "," .Values.dutyUsers.monday -}} ]
      - [ {{- join "," .Values.dutyUsers.tuesday -}} ]
      - [ {{- join "," .Values.dutyUsers.wednesday -}} ]
      - [ {{- join "," .Values.dutyUsers.thursday -}} ]
      - [ {{- join "," .Values.dutyUsers.friday -}} ]
      - [ {{- join "," .Values.dutyUsers.saturday -}} ]
